//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialsJAMCH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MaterialsEntitiesN : DbContext
    {
        public MaterialsEntitiesN()
            : base("name=MaterialsEntitiesN")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<PartNumbers> PartNumbers { get; set; }
    
        public virtual int SPCreateBuilding(string building)
        {
            var buildingParameter = building != null ?
                new ObjectParameter("Building", building) :
                new ObjectParameter("Building", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPCreateBuilding", buildingParameter);
        }
    
        public virtual int SPCreateCustomer(string customer, string prefix, Nullable<int> fKBuilding, Nullable<bool> available)
        {
            var customerParameter = customer != null ?
                new ObjectParameter("Customer", customer) :
                new ObjectParameter("Customer", typeof(string));
    
            var prefixParameter = prefix != null ?
                new ObjectParameter("Prefix", prefix) :
                new ObjectParameter("Prefix", typeof(string));
    
            var fKBuildingParameter = fKBuilding.HasValue ?
                new ObjectParameter("FKBuilding", fKBuilding) :
                new ObjectParameter("FKBuilding", typeof(int));
    
            var availableParameter = available.HasValue ?
                new ObjectParameter("Available", available) :
                new ObjectParameter("Available", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPCreateCustomer", customerParameter, prefixParameter, fKBuildingParameter, availableParameter);
        }
    
        public virtual int SPCreatePartNumber(string partNumber, Nullable<int> fKCustomer, Nullable<bool> available)
        {
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var fKCustomerParameter = fKCustomer.HasValue ?
                new ObjectParameter("FKCustomer", fKCustomer) :
                new ObjectParameter("FKCustomer", typeof(int));
    
            var availableParameter = available.HasValue ?
                new ObjectParameter("Available", available) :
                new ObjectParameter("Available", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPCreatePartNumber", partNumberParameter, fKCustomerParameter, availableParameter);
        }
    
        public virtual ObjectResult<SPGetPartNumbers_Result> SPGetPartNumbers(string partNumber, string customer, Nullable<bool> available)
        {
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var customerParameter = customer != null ?
                new ObjectParameter("Customer", customer) :
                new ObjectParameter("Customer", typeof(string));
    
            var availableParameter = available.HasValue ?
                new ObjectParameter("Available", available) :
                new ObjectParameter("Available", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetPartNumbers_Result>("SPGetPartNumbers", partNumberParameter, customerParameter, availableParameter);
        }
    }
}
